### ISSUE TITLE
feature-request: Delayed destruction

### ISSUE THREAD

**Issue by akutz** [crosscloudci/cross-cloud#162]
Hi All,

Due to some previous issues, as well as the current #161, we're trying to figure out the best method to delay the destruction of our environments. PR #154 provides the ability to destroy an environment without the need for the Terraform state, so one method would be to simply disable the destroy step for vSphere and let us manually remove resources a day or two later.

However, I think this is a feature that may also add value to other platforms. The fact is, it's hard to debug failed deployments when the resources are no longer present. Logs may be attached to those resources, and when the resources are destroyed, so too are the logs.

This is potentially a priority issue for VMware.

Thank you!

**Comment by akutz** [comment]
Hi All,

After a few hours round-the-bin with internal support here at VMware, they've concluded there is little they are able to do unless there are logs associated with failed deployments. I am going to submit a PR to make the destruction of vSphere environments dependent upon an environment variable. The default value will be to **not** destroy the environment.

**Comment by taylor** [comment]
Reference pull request for skipping destroy https://github.com/crosscloudci/cross-cloud/pull/163

**Comment by akutz** [comment]
Hi @taylor,

Done and done. I also made it so `DESTROY_SKIP` is checked in case you want to generalize the feature.
