### ISSUE TITLE
vsphere: Builds failing due to stale Cross-Cloud-side git cache

### ISSUE THREAD

**Issue by akutz** [crosscloudci/cross-cloud#173]
The most recent builds are failing for vSphere again due to out-of-address errors regarding AWS load balancers and elastic IPs. However, these were removed in #169. The only explanation is that the Git cache where these builds are running is stale and does not include the change to remove the EIPs.

This is P0 for us. Thank you.

@clintkitson @figo @lixuna

**Comment by lixuna** [comment]
@akutz, that change [commit e48d597](https://github.com/crosscloudci/cross-cloud/commit/daf981cd33cf51eee9a16f1045806c45af580678) has not yet been promoted to production.

It’s currently in testing with other fixes and updates to cross-cloud.

Would you like us to temporarily remove vSphere from the dashboard until #169 is merged to production?

cc @taylor @denverwilliams

**Comment by akutz** [comment]
Hi @lixuna,

I'll let @clintkitson make that decision. In the future we would appreciate if there was more clear communication as to what occurs after @denverwilliams merges a change. His comments on the PR sure made it sound as if the fix was in:

**Comment by denverwilliams** [comment]
@akutz 
These changes have now been promoted to production.

**Comment by akutz** [comment]
Hi @denverwilliams,

Thank you. I apologize if I misunderstood your previous communique. I assumed that merging the change into `master` resulted in it being use for your prod environment. I will remember that this is not the case for future events. Thank you again.
