### ISSUE TITLE
Build better e2e test for CoreDNS (possibly remove Dockerfile + ./e2e/ from ci-* branches)

### ISSUE THREAD

**Issue by hh** [crosscloudci/cross-cloud#47]

**Comment by taylor** [comment]
@denverwilliams, upstream e2e test https://github.com/coredns/coredns/issues/993.

**Comment by fturib** [comment]
What are the e2e tests ran for CoreDNS in  CrossCloudCI Project ?

NOTE: we met during KubeCon at SIG cross-cloud ci meeting, and we agreed to continue that conversation using an Issue in this project.
As I see this issue about the same subject still open, I piggy back on this issue.

The questions I have are:
1- What e2e tests are you triggering for the CoreDNS project ? 
=> Question below this one is: how can we organize our e2e tests so they are periodically ran by CrossCloudCI.
=> We have some e2e tests that concerned CoreDNS only, some others that concern CoreDNS as a DNS Server for K8s.
2- Is there a way to trigger a CrossCloudCI e2e test on coredns from a simple word in the Gighub PR (let say something like : /e2e).
