### ISSUE TITLE
Add ONAP support to CNCF CI Cross Cloud Pipeline

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/cross-cloud#93]

**Comment by lixuna** [comment]
As discussed in the ONAP + CNCF Cross Cloud Demo on Wed, Oct 11th, here is a ticket with next steps to adding ONAP Support to the pipeline:

**Step 1: (start with one component)**

- Install one small component to see if they can get it to work (orchestration - made up of 2 containers, db and business logic)

- Deploy 2 containers with helm

- Deploy a simple robot test container (to validate that orchestration component is healthy)

---

Roger and the ONAP Team, 

Let's use this ticket to outline the steps to take once the small component is ready for the CNCF WI Working Group. 

Thank you for meeting with us today,
Lucina

Lucina Stricko
Partner / Project Manager
vulk.coop

**Comment by obriensystems** [comment]
ONAP tracking JIRA for integration work
https://jira.onap.org/browse/OOM-357
