### ISSUE TITLE
Add support for Packet+ARM

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/cross-cloud#96]

**Comment by vielmetti** [comment]
Happy to help.

**Comment by vielmetti** [comment]
Any progress since October?

**Comment by lixuna** [comment]
Thank you for joining the CNCF CI WG meeting today, Ed. 

We are looking forward to scheduling a demo of the cross-cloud project with you and the Packet+Arm team. 

Here are some CNCF CI Cross-Cloud resources that you are welcome to share with your team:

- v1.0 Pipeline README: https://github.com/cncf/cross-cloud/blob/master/README.md

- v1.0 FAQ: https://github.com/cncf/cross-cloud/blob/master/FAQ.md

- Dashboard Design Mocks:
https://github.com/cncf/cross-cloud/blob/master/DASHBOARD.md

- CNCF CI Public Mailing List:
https://lists.cncf.io/mailman/listinfo/cncf-ci-public

- Slide Deck attached as PDF

- Wednesday, December 6 • 7:30pm - 9:00pm [BoF: Cross-Cloud Continuous Integration (CI) of all CNCF Projects Across All Public Clouds](https://kccncna17.sched.com/event/D4Ze/bof-cross-cloud-continuous-integration-ci-of-all-cncf-projects-across-all-public-clouds-hosted-by-chris-mcclimans-and-dan-kohn)

[CNCF CI WG Tuesday, November 28th, 2017.pdf](https://github.com/cncf/cross-cloud/files/1510799/CNCF.CI.WG.Tuesday.November.28th.2017.README.pdf)



We hope that these resources are helpful and we look forward to continuing the conversation with you and your team.

Thanks again,
Lucina

Lucina Stricko
Partner / Project Manager
vulk.coop

**Comment by vielmetti** [comment]
Hi @lixuna - when is the next CNCF CI WG? Looking forward to scheduling our introductory call, which I will do after my travels to New York complete.

**Comment by lixuna** [comment]
Good morning @vielmetti!

I'm sorry we missed you in today's call. We reviewed the feedback gathered at KubeCon.

CI WG Calls are typically held on the 2nd and 4th Tuesday of the month. We will not have a call on Tuesday, December 26th due to the holidays.

Our next CI WG will be on Tuesday, January 9th at 8am Pacific. 

Looking forward to our intro call!

**Comment by lixuna** [comment]
Update: 

Arm support has been added to Kubernetes Stable and head clusters on cncf.ci in [v2.3.0](https://github.com/crosscloudci/crosscloudci/wiki/CNCF-CI-v2.3.0-Release-Notes)

Arm support will be added to the CNCF projects on cncf.ci incrementally, starting with CoreDNS [#133](https://github.com/crosscloudci/crosscloudci/issues/133) - which is currently in progress.
